language: java
jdk:
  - openjdk11
branches:
  only:
    - main
before_install:
  - chmod +x gradlew

# travis ci 서버의 home
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.gradle"

script:
  - "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * #before_deploy로 이동 후 전체 압축
  - cd ../ && mkdir -p deploy #상위 디렉토리로 이동 후 deploy 디렉토리 새성
  - mv before-deploy/before-deploy.zip deploy/bday2.zip #deploy로 zip파일 이동

deploy:
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
    bucket: bday2-springboot-build #s3 버킷 이름
    region: ap-northeast-2
    skip_cleanup: true
    acl: private #zip 파일접근을 private
    local_dir: deploy #before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      branch: main

  - provider: codedeploy
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
    bucket: bday2-springboot-build #s3 버킷 이름
    key: bday2.zip
    bundle_type: zip #압축 확장자
    application: bday2 #웹 콘솔에서 등록한 codedeploy 애플리케이션
    deployment_group: bday2-group #웹 콘솔에서 등록한 codedeploy 배포그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      branch: main

# ci 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - iamgood147@gmail.com
